[package]
name = "espflash"
version = "1.2.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"
rust-version = "1.56"
license = "GPL-2.0"
description = "ESP8266 and ESP32 serial flasher"
repository = "https://github.com/esp-rs/espflash"
exclude = ["tests/data"]

[[bin]]
name = "espflash"
path = "src/main.rs"

[lib]

[dependencies]
binread = "2"
bytemuck = { version = "1", features = ["derive"] }
indicatif = "0.16"
md5 = "0.7"
clap = { version = "3.0", features = ["derive"] }
serialport = { git = "https://gitlab.com/spookyvision1/serialport-rs", rev = "7816e282" }
sha2 = "0.10"
slip-codec = "0.3"
thiserror = "1"
xmas-elf = "0.8"
serde = { version = "1", features = ["derive"] }
serde_plain = "1"
toml = "0.5"
strum = "0.23"
strum_macros = "0.23"
csv = "1"
regex = "1"
flate2 = "1"
miette = { version = "3", features = ["fancy"] }
crossterm = "0.22"
directories-next = "2"
dialoguer = "0.9"
serde-hex = "0.1"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }"
pkg-fmt = "bin"
